const sounds = [
    {
        keyCode:81,
        letter:"Q",
        src:"https://s3.amazonaws.com/freecodecamp/drums/Heater-1.mp3"
    },
    {
        keyCode:87,
        letter:"W",
        src:"https://s3.amazonaws.com/freecodecamp/drums/Heater-2.mp3"
    },
    {
        keyCode:69,
        letter:"E",
        src:"https://s3.amazonaws.com/freecodecamp/drums/Heater-3.mp3"
    },
    {
        keyCode:65,
        letter:"A",
        src:"https://s3.amazonaws.com/freecodecamp/drums/Heater-4_1.mp3"
    },
    {
        keyCode:83,
        letter:"S",
        src:"https://s3.amazonaws.com/freecodecamp/drums/Heater-6.mp3"
    },
    {
        keyCode:68,
        letter:"D",
        src:"https://s3.amazonaws.com/freecodecamp/drums/Dsc_Oh.mp3"
    },
    {
        keyCode:90,
        letter:"Z",
        src:"https://s3.amazonaws.com/freecodecamp/drums/Kick_n_Hat.mp3"
    },
    {
        keyCode:88,
        letter:"X",
        src:"https://s3.amazonaws.com/freecodecamp/drums/RP4_KICK_1.mp3"
    },
    {
        keyCode:67,
        letter:"C",
        src:"https://s3.amazonaws.com/freecodecamp/drums/Cev_H2.mp3"
    }
];


export default sounds;